### ISSUE TITLE
I want to edit start.sh for my own usage but having trouble

### ISSUE THREAD

**Issue by nathanv** [Boran/docker-drupal#10]
I forked it and then trying to use https://quay.io/repository/nathanv/drupal_test/build/8ea66aec-d8fe-47ef-999f-0ec37551f25c to have my own docker build but I'm getting errors "A build step failed: files/drupal-7: no such file or directory" 
Any ideas on how to fix?

**Comment by Boran** [comment]
See the bottom of the Readme for creating a custom build: a copy of drupal7 needs to be downloaded and included  in the build, so that D7 sites can be installed quickly.

An alternative to changing start.sh is to inherit boran/drupal with a new image name and in that image add a /custom.sh. /start.sh will execute custom.sh at the end, if it exists.

**Comment by nathanv** [comment]
Thank you kindly! Closing.
